[alias]
# Development
serve = "run --target wasm32-unknown-unknown"
watch = "watch -x check -x test"

# Testing and validation
test = "test --all-targets --all-features"
check-all = "check --all-targets --all-features"
lint = "clippy --all-targets --all-features -- -D warnings"

# Build and release
release = "build --release --target wasm32-unknown-unknown"